title: Tom Hodson
feed_title: Tom Hodson's Blog
description: Physics, Programming and Baking.
url: https://thomashodson.com

feed:
  posts_limit: 100
  update_period: monthly
  update_frequency: 1

exclude: ["env/", ]
host: 0.0.0.0

collections:
  cv_entries:
    output: true
  thesis:
    output: true
  talks:
    output: true
  projects:
    output: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false
    css_class: 'highlight'
    span:
      wrap: span


include:
  - node_modules


plugins:
  - jekyll-redirect-from
  - jekyll-last-modified-at


