title: Tom Hodson
description: Physics, Programming and Baking.
url: http://thomashodson.com/
author:
  twitter: T_Hodson

exclude: ["env/", ]
host: 0.0.0.0

collections:
  cv_entries:
    output: true

plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-feed
  - jekyll-redirect-from

feed:
  posts_limit: 20