title: Tom Hodson
description: Physics, Programming and Baking.
url: https://thomashodson.com
author:
  twitter: T_Hodson

exclude: ["env/", ]
host: 0.0.0.0

collections:
  cv_entries:
    output: true
  thesis:
    output: true
  talks:
    output: true
  projects:
    output: true

include:
  - node_modules

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - flexible_include


feed:
  posts_limit: 100