title: Tom Hodson
feed_title: Tom Hodson's Blog
description: Physics, Programming and Baking.
url: https://thomashodson.com

feed:
  posts_limit: 100
  update_period: monthly
  update_frequency: 1

exclude: ["env/", ]
host: 0.0.0.0

collections:
  cv_entries:
    output: true
  thesis:
    output: true
  talks:
    output: true
  projects:
    output: true

kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: false

flexible_include:
  die_on_flexible_include_error: false

include:
  - node_modules

plugins:
  # - jekyll-feed
  - jekyll-redirect-from
  - flexible_include
  - kramdown-syntax-coderay
  - jekyll-last-modified-at


