title: Tom Hodson
description: Physics, Programming and Baking.
url: https://thomashodson.com
author:
  twitter: T_Hodson

exclude: ["env/", ]
host: 0.0.0.0

collections:
  cv_entries:
    output: true
  thesis:
    output: true
  talks:
    output: true
  projects:
    output: true

node_modules:
  modules_dir: node_modules
  assets:
    js: assets/js
    css: assets/css
  copy:
  - source: three/
    target: assets/js/three/
  - source: es-module-shims/
    target: assets/js/es-module-shims/


plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - flexible_include
#   - jekyll-node-module


feed:
  posts_limit: 100